<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Cntryl.Pants.CompatibilityHarness</AssemblyName>
    <RootNamespace>Cntryl.Pants.CompatibilityHarness</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Pants\Pants.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cntryl.Pants.CompatibilityHarness.Tests" />
  </ItemGroup>

</Project>
