<Project>
  <Import Project="../Directory.Build.props"/>

  <PropertyGroup>
    <AssemblyName>Cntryl.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>
</Project>
