services:

  sqrzl:
    hostname: sqrzl
    image: ghcr.io/sqrzl/sqrzl-emulator@sha256:876e017f850e53f3f4172cae459982cfe9435584fcb8e4640120b2e5fabfc624
    ports:
      - "${PANTS_SQRZL_API_PORT:-9000}:9000"
      - "${PANTS_SQRZL_UI_PORT:-9001}:9001"
    environment:
      SQRZL_BLOBS_PATH: /app/blobs
      SQRZL_ACCESS_KEY_ID: admin
      SQRZL_SECRET_ACCESS_KEY: easy-peasy
      SQRZL_BUCKET_LIST: pants-sqrzl-s3,pants-sqrzl-azure,pants-sqrzl-gcs-xml,pants-sqrzl-gcs-json
    volumes:
      - sqrzl-blobs:/app/blobs

volumes:
  sqrzl-blobs:
