<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
    <ProjectReference Include="..\Pants.Core\Pants.Core.csproj"/>
  </ItemGroup>
</Project>
