<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="Microsoft.Extensions.Configuration"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\bench\Pants.Benches\Cntryl.Pants.Benches.csproj"/>
    <ProjectReference Include="..\..\src\Pants.Abstractions\Pants.Abstractions.csproj"/>
    <ProjectReference Include="..\..\src\Pants.Core\Pants.Core.csproj"/>
    <ProjectReference Include="..\..\src\Pants.DependencyInjection\Pants.DependencyInjection.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="Fixtures/Compatibility/**/*" CopyToOutputDirectory="PreserveNewest"/>
    <None Update="MidgeContractManifest.json" CopyToOutputDirectory="PreserveNewest"/>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>

</Project>
