<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet"/>
    <ProjectReference Include="..\..\src\Pants\Pants.csproj"/>
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>Cntryl.Pants.Benches</AssemblyName>
    <RootNamespace>Cntryl.Pants.Benches</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
