<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" VersionOverride="10.0.12" />
    <ProjectReference Include="..\..\src\Pants.Core\Pants.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cntryl.Pants.Tests"/>
  </ItemGroup>

</Project>
